default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: practice-message_development
test:
  <<: *default
  database: practice-message_test

production:
  <<: *default
  database: practice-message_production
  username: practice-message
  password: <%= ENV['PRACTICE-MESSAGE_DATABASE_PASSWORD'] %>
